### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Soyvor**
Updates the Java Learning Readme

### CODE REVIEW

**Comment by spidey0101** [comment]
Everything is okay but shouldn't be it nice if we could add our mail I'd so that we can get the feedback or do u have any other method where they can share their feedback here itself?

**Review by spidey0101 — CHANGES_REQUESTED** [review]
pls check my previous comment.

**Comment by Soyvor** [comment]
> Everything is okay but shouldn't be it nice if we could add our mail I'd so that we can get the feedback or do u have any other method where they can share their feedback here itself?

We can have a container for feedback or just add a small mailto: tag for getting the feedback over mail ig that would be enough

**Comment by Soyvor** [comment]
Let me recreate the readme

**Review by Soyvor — COMMENTED** [review]
Committed again with changes

**Comment by Soyvor** [comment]
any update?

**Comment by spidey0101** [comment]
Done

**Pull request merged**
