### PR TITLE
Added directories 

### PR DESCRIPTION
**Pull request by kom-senapati**
Also added respective readme files.

### CODE REVIEW

**Comment by spidey0101** [comment]
Please explain in detail what you are planning to contribute

**Comment by kom-senapati** [comment]
I want to add a directory structure and their readmes so that developers can contribute easily and learners can navigate easily.

**Comment by spidey0101** [comment]
we have updated the readme file pls look at it.

**Comment by kom-senapati** [comment]
I have added more files with instructions.

**Comment by spidey0101** [comment]
Make files as per the main page and try to create seperate folders fro each of them with a short description on it

**Comment by kom-senapati** [comment]
I created this structure 
image
so that it would be easy to navigate your repo. Can you please tell what changes you want here ?

**Comment by spidey0101** [comment]
Create folders for Algorithms, Basic concepts, additional concepts,Design patterns,OOPs. Instead of these.
I hope you get it
And atlast a seperate folder for other ppl to project contribution

**Comment by kom-senapati** [comment]
Ok, I will do that but I created these as from the readme.md I knew about the structure and created them.

**Pull request closed without merging**
